### PR TITLE
Implemented most methods of wxFileDialog

### PR DESCRIPTION
**Pull request by mrcdk**
Methods that aren't implemented:
- `getExtraControl()` http://docs.wxwidgets.org/trunk/classwx_file_dialog.html#a0b6e2bfdb5997e74c99fcf6d3249a798
- `setExtraControlCreator()` http://docs.wxwidgets.org/trunk/classwx_file_dialog.html#aa312b8ae7961060c3116457c6334b527
- `getFilenames()` and `getPaths()` http://docs.wxwidgets.org/trunk/classwx_file_dialog.html#a282cf846facc9eae4682c43627229e9c I'm not sure how to do that.

Also, `filterIndex` seems to throw an error if there are no wildcards.

Only tested on a Ubuntu 16.04 using latest dev Haxe and hxcpp.

Should be enough for issue #29

### CODE REVIEW

**Comment by ianharrigan** [comment]
Great! Any chance you can fix the checkstyle? Line is 226 chars long, which is 1 to many... Might make sense to break it up / simplify it anyway as even 225 is pretty long. (Although i get that its just a log line)

**Comment by ianharrigan** [comment]
Also you can ignore appveyor checks... they arent setup so will always fail (im removed it from the project for now)

**Comment by ibilon** [comment]
Travis succeeded and code looks good, thanks for the contribution!

**Comment by mrcdk** [comment]
okay, done @ianharrigan

**Comment by ianharrigan** [comment]
Perfect... thanks @mrcdk

**Pull request merged**
