### PR TITLE
Extract the externs into their own package

### PR DESCRIPTION
**Pull request by ibilon**
I couldn't test the hxcpp compilation for my last commit, should work but I'll report tonight after I check.

All the externs are now in the  `wx.widgets` package,
changed from `XRef and X` to `X and XImpl`,
I put back the `cpp::Reference` in the `@:native` since hxcpp can deal with it now,
the styles were extracted too.

Haven't touched the hierarchy (#14) yet.

### CODE REVIEW

**Comment by ianharrigan** [comment]
Oh? the `cpp::Reference` has been fixed?? Where in hxcpp?

**Comment by ibilon** [comment]
You can see hugh's comment here https://github.com/HaxeFoundation/hxcpp/issues/359
linking to this commit https://github.com/HaxeFoundation/hxcpp/commit/ab267e10161cc7a9bb2911593531654db1b1dbb7

**Comment by ianharrigan** [comment]
Nice. Feels "nicer" to be using Refs rather than pointers... Will merge this shortly and check it out. Does this mean hxcpp has be be git version?

**Comment by ibilon** [comment]
Unsure, will have to test.

Because I modified the way the classes are extended like in Hugh's comment,
for instance it's now class `CheckBoxImpl extends Window` and not `class CheckBoxImpl extends WindowImpl`, so you don't need the cast anymore actually, so it could work with hxcpp haxelib.

**Comment by ianharrigan** [comment]
Great, ill check it out on linux and mac later tonight. +1

**Comment by ibilon** [comment]
Ok so my last commit does indeed work,
but it does require a git version of hxcpp,
the casts were not required so I removed them.

I also moved a couple of classes I forgot.

**Comment by ianharrigan** [comment]
Ok, great... ill merge it now. I havent had a chance to test it myself, but ill make the assumption it works... :)

**Comment by ianharrigan** [comment]
So just downloaded and tested... works great... thanks loads @ibilon!

**Pull request merged**
